#!/usr/bin/env python3
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from project_workflow.config import get_settings
from project_workflow.infrastructure.db.session import ensure_schema, get_engine

__doc__ = """Create schema/tables from ORM models and stamp Alembic head.

Used by the Docker Compose `migrate` service so the initial Postgres
schema is created without relying on autogenerated Alembic DDL.
Future migrations are still applied via `alembic upgrade head`.
"""


def main() -> int:
    settings = get_settings()
    engine = get_engine(settings.DATABASE_URL)
    ensure_schema(engine)
    protocol = settings.DATABASE_URL.split(":")[0]
    print(f"Schema ensured for {protocol}")

    # Stamp Alembic head so future migrations start from the correct baseline.
    env = os.environ.copy()
    if settings.DATABASE_URL:
        env["DATABASE_URL"] = settings.DATABASE_URL
    result = subprocess.run(
        ["alembic", "stamp", "head"],
        cwd=Path(__file__).resolve().parent.parent,
        env=env,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("alembic stamp failed:", result.stderr, file=sys.stderr)
        return result.returncode
    print("Alembic version stamped to head")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
