"""initial schema

Revision ID: 57316bf44b1a
Revises: 
Create Date: 2026-06-21 14:43:30.436445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57316bf44b1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cli_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('task_key', sa.String(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_default', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('is_default IN (0, 1)', name='ck_workflows_is_default'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_time_min', sa.Integer(), server_default='0', nullable=True),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('next_recommendation', sa.Text(), nullable=True),
    sa.Column('parallel_with', sa.String(), nullable=True),
    sa.Column('rollback_target', sa.String(), nullable=True),
    sa.Column('execution_type', sa.String(), server_default='sync', nullable=True),
    sa.Column('is_seed_managed', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("execution_type IN ('sync', 'parallel')", name='ck_phases_execution_type'),
    sa.CheckConstraint('is_seed_managed IN (0, 1)', name='ck_phases_is_seed_managed'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_patterns', sa.String(), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'description', name='uq_checks_phase_description')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'description', name='uq_evidence_phase_description')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('step_num', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('execution_type', sa.String(), server_default='sync', nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.CheckConstraint("execution_type IN ('sync', 'parallel')", name='ck_instructions_execution_type'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'step_num', name='uq_instructions_phase_step')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_phase', sa.String(), server_default='-1', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('updated_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.CheckConstraint("status IN ('active', 'done', 'blocked')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_key')
    )
    op.create_table('supervisor_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('report', sa.Text(), server_default='', nullable=False),
    sa.Column('covered', sa.Text(), server_default='[]', nullable=False),
    sa.Column('missing', sa.Text(), server_default='[]', nullable=False),
    sa.Column('blockers', sa.Text(), server_default='[]', nullable=False),
    sa.Column('next_phase_id', sa.Integer(), nullable=True),
    sa.Column('rollback_phase_id', sa.Integer(), nullable=True),
    sa.Column('context_snapshot', sa.Text(), server_default='{}', nullable=False),
    sa.Column('response', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.CheckConstraint("verdict IN ('pass', 'partial', 'blocked', 'rollback', 'delegate')", name='ck_supervisor_runs_verdict'),
    sa.ForeignKeyConstraint(['next_phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['rollback_phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'done', 'partial', 'blocked', 'rollback', 'delegated')", name='ck_task_history_status'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'phase_id', name='uq_task_history_task_phase')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_history')
    op.drop_table('supervisor_runs')
    op.drop_table('tasks')
    op.drop_table('instructions')
    op.drop_table('evidence')
    op.drop_table('checks')
    op.drop_table('projects')
    op.drop_table('phases')
    op.drop_table('workflows')
    op.drop_table('cli_history')
    op.drop_table('agents')
    # ### end Alembic commands ###
